<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-21 at 11:05:47.
 */
class VF_GroupFieldTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var VF_GroupField
     */
    protected $object;

    protected $id;
    protected $name;
    protected $type;
    protected $label;
    protected $value;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->id = Random::string();
        $this->name = Random::string();
        $this->type = "radio"; // or 'checklist'
        $this->label = Random::string();
        $this->value = Random::string();

        $this->object = new VF_GroupField($this->id, $this->name, $this->type, $this->label, $this->value);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers VF_GroupField::toHtml
     * @todo   Implement testToHtml().
     */
    public function testToHtml()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
