<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-21 at 11:08:29.
 */
class VF_SelectTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var VF_Select
     */
    protected $object;
    protected $type;
    protected $label;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->name = Random::string();
        $this->type = VFORM_SELECT_LIST;

        $this->object = new VF_Select($this->name, $this->type);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers VF_Select::toHtml
     * @todo   Implement testToHtml().
     */
    public function testToHtml()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers VF_Select::__toHtml
     * @todo   Implement test__toHtml().
     */
    public function test__toHtml()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers VF_Select::toJS
     * @todo   Implement testToJS().
     */
    public function testToJS()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers VF_Select::addField
     * @todo   Implement testAddField().
     */
    public function testAddField()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers VF_Select::addFieldObject
     * @todo   Implement testAddFieldObject().
     */
    public function testAddFieldObject()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers VF_Select::addGroup
     * @todo   Implement testAddGroup().
     */
    public function testAddGroup()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
