<?php

namespace ValidFormBuilder\Tests;

use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use ValidFormBuilder\Button;
use ValidFormBuilder\Collection;
use ValidFormBuilder\Navigation;
use ValidFormBuilder\StaticText;

/**
 * Comprehensive coverage for {@link \ValidFormBuilder\Navigation}.
 *
 * Navigation is a container for form buttons (submit/reset) and optional
 * raw HTML injected via addHtml(). It extends Base and renders as a
 * `<div class="vf__navigation">` wrapping its children.
 *
 * Surface covered:
 * - Constructor: meta storage, empty fields collection, auto-generated id in meta.
 * - addButton(): creates Button child with parent wiring.
 * - addHtml(): creates StaticText child with parent wiring.
 * - Placeholders: isValid (always true), getValue (always true), getId (null),
 *   isDynamic (false), getType (0), getHeader (null).
 * - hasFields(): false when empty, true when populated.
 * - getFields(): returns collection.
 * - toHtml: wrapper div with vf__navigation class, children rendered inside.
 * - toJS: concatenates child JS + emits addElement for the navigation itself.
 *
 * Security audit:
 * - addHtml() passes raw HTML through StaticText — by design (method name is
 *   "addHtml"), but noted as a footgun if developers pass user input.
 * - Button labels in addButton() are developer-defined.
 * - No direct user input handling, no $_REQUEST / $_FILES.
 */
class NavigationTest extends TestCase
{
    use HtmlAssertionsTrait;

    // --------------------------------------------------------------
    // Constructor
    // --------------------------------------------------------------

    #[Test]
    public function constructorInitialisesEmptyFieldsCollection(): void
    {
        $nav = new Navigation();

        $this->assertInstanceOf(Collection::class, $nav->getFields());
        $this->assertSame(0, $nav->getFields()->count());
    }

    #[Test]
    public function constructorStoresMetaAndSetsAutoGeneratedId(): void
    {
        $nav = new Navigation(['class' => 'custom-nav']);

        $this->assertSame('custom-nav', $nav->getMeta('class'));
        // Constructor calls setMeta("id", $this->getName()) which auto-generates a name.
        $this->assertNotEmpty($nav->getMeta('id'));
    }

    // --------------------------------------------------------------
    // addButton / addHtml
    // --------------------------------------------------------------

    #[Test]
    public function addButtonCreatesButtonChildAndReturnsIt(): void
    {
        $nav = new Navigation();
        $btn = $nav->addButton('Submit');

        $this->assertInstanceOf(Button::class, $btn);
        $this->assertSame(1, $nav->getFields()->count());
        $this->assertSame('Submit', $btn->getLabel());
    }

    #[Test]
    public function addButtonSetsNavigationAsParent(): void
    {
        $nav = new Navigation();
        $btn = $nav->addButton('Submit');

        $this->assertSame($nav, $btn->getMeta('parent'));
    }

    #[Test]
    public function addHtmlCreatesStaticTextChildAndReturnsIt(): void
    {
        $nav = new Navigation();
        $html = $nav->addHtml('<span>or</span>');

        $this->assertInstanceOf(StaticText::class, $html);
        $this->assertSame(1, $nav->getFields()->count());
    }

    #[Test]
    public function addHtmlSetsNavigationAsParent(): void
    {
        $nav = new Navigation();
        $html = $nav->addHtml('<span>or</span>');

        $this->assertSame($nav, $html->getMeta('parent'));
    }

    #[Test]
    public function multipleChildrenAccumulateInOrder(): void
    {
        $nav = new Navigation();
        $btn1 = $nav->addButton('Back');
        $nav->addHtml('<span class="separator">|</span>');
        $btn2 = $nav->addButton('Next');

        $this->assertSame(3, $nav->getFields()->count());
        $this->assertSame($btn1, $nav->getFields()->getFirst());
        $this->assertSame($btn2, $nav->getFields()->getLast());
    }

    // --------------------------------------------------------------
    // Placeholders
    // --------------------------------------------------------------

    #[Test]
    public function isValidAlwaysReturnsTrue(): void
    {
        $nav = new Navigation();

        $this->assertTrue($nav->isValid());
    }

    #[Test]
    public function getValueAlwaysReturnsTrue(): void
    {
        $nav = new Navigation();

        $this->assertTrue($nav->getValue());
    }

    #[Test]
    public function getIdReturnsNull(): void
    {
        $nav = new Navigation();

        // Note: the constructor sets meta["id"] via setMeta, but getId() does not
        // consult meta — it returns null. toJS() uses getMeta("id") directly.
        $this->assertNull($nav->getId());
    }

    #[Test]
    public function isDynamicReturnsFalse(): void
    {
        $nav = new Navigation();

        $this->assertFalse($nav->isDynamic());
    }

    #[Test]
    public function getTypeReturnsZero(): void
    {
        $nav = new Navigation();

        $this->assertSame(0, $nav->getType());
    }

    #[Test]
    public function getHeaderReturnsNull(): void
    {
        $nav = new Navigation();

        $this->assertNull($nav->getHeader());
    }

    // --------------------------------------------------------------
    // hasFields / getFields
    // --------------------------------------------------------------

    #[Test]
    public function hasFieldsReturnsFalseWhenEmpty(): void
    {
        $nav = new Navigation();

        $this->assertFalse($nav->hasFields());
    }

    #[Test]
    public function hasFieldsReturnsTrueWhenPopulated(): void
    {
        $nav = new Navigation();
        $nav->addButton('Submit');

        $this->assertTrue($nav->hasFields());
    }

    // --------------------------------------------------------------
    // toHtml
    // --------------------------------------------------------------

    #[Test]
    public function toHtmlRendersWrapperDivWithNavigationClass(): void
    {
        $nav = new Navigation();
        $nav->addButton('Submit');

        $xpath = $this->parseHtml($nav->toHtml());

        // `//div[contains(concat(" ", normalize-space(@class), " "), " vf__navigation ")]`
        // — the outer wrapper div whose class list includes the `vf__navigation` token.
        $wrapper = $xpath->query('//div[contains(concat(" ", normalize-space(@class), " "), " vf__navigation ")]')->item(0);
        $this->assertNotNull($wrapper);
    }

    #[Test]
    public function toHtmlRendersButtonChildrenInsideWrapper(): void
    {
        $nav = new Navigation();
        $nav->addButton('Back');
        $nav->addButton('Next');

        $xpath = $this->parseHtml($nav->toHtml());

        // `//div//input[@type]` — all input elements anywhere inside the wrapper.
        // Button renders as `<input type="submit|button" ...>`.
        $inputs = $xpath->query('//div//input[@type]');
        $this->assertSame(2, $inputs->length);
        $this->assertSame('Back', $inputs->item(0)->getAttribute('value'));
        $this->assertSame('Next', $inputs->item(1)->getAttribute('value'));
    }

    #[Test]
    public function toHtmlRendersHtmlChildrenInsideWrapper(): void
    {
        $nav = new Navigation();
        $nav->addButton('Submit');
        $nav->addHtml('<span class="hint">Press submit to continue</span>');

        $xpath = $this->parseHtml($nav->toHtml());

        // `//div//span[@class="hint"]` — the injected HTML span inside the wrapper.
        $span = $xpath->query('//div//span[@class="hint"]')->item(0);
        $this->assertNotNull($span);
        $this->assertSame('Press submit to continue', trim($span->textContent));
    }

    // --------------------------------------------------------------
    // toJS
    // --------------------------------------------------------------

    #[Test]
    public function toJsEmitsAddElementCallWithMetaId(): void
    {
        $nav = new Navigation();
        $nav->addButton('Submit');

        $js = $nav->toJS();

        // Navigation emits its own addElement() call using getMeta("id").
        $this->assertSame(1, substr_count($js, 'objForm.addElement'));
    }

    // --------------------------------------------------------------
    // Security
    // --------------------------------------------------------------

    #[Test]
    public function addHtmlRendersRawHtmlByDesign(): void
    {
        // NOTE: addHtml() passes the string through StaticText which renders it
        // as raw HTML — this is intentional (the method is named "addHtml").
        // If a developer passes user input to addHtml(), it's an XSS footgun.
        // The library cannot prevent this without breaking the documented purpose,
        // but we document the behaviour here as an explicit contract.
        $nav = new Navigation();
        $nav->addHtml('<script>alert("xss")</script>');

        $html = $nav->toHtml();

        // The raw script tag IS present in the rendered output — this is by design.
        // Developers must never pass user input to addHtml().
        $this->assertStringContainsString('<script>', $html);
    }
}
