name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PHP_VERSION: '8.2'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Set up PHP 8.2
        uses: shivammathur/setup-php@2
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: Install Composer dependencies
        uses: php-actions/composer@v6
        with:
          php-version: ${{ env.PHP_VERSION }}
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.PAT }}"} }'

      - name: Install Travis CLI
        run: gem install travis

      - name: Validate Travis install
        run: travis --version

      - name: Run tests
        run: vendor/bin/phpunit
